### ISSUE TITLE
Initialize Isotope.JS sorting element for data object with image

### ISSUE THREAD

**Issue by evanwexler** [ExplainCorp/poverty_line#1]
I think we'll need an object model that can contain a few different types of data and image URLs
I'm uploading a few images from three different households. Let's see if we can make them sortable by the house rent expenditure number, which I've uploaded.

**Comment by evanwexler** [comment]
Data to use is here: data/EXAMPLE_DATA.csv
Images to use are here: assets/
Each image number and folder refers to the household number in the data sheet

**Comment by talyellin** [comment]
Fixed, see readme.md for updates
